apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      initContainers:
        - name: {{ .Values.name }}-init
          image: {{ .Values.image.initRepository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ toYaml .Values.env | indent 12 }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: {{ .Values.listeningPort }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ toYaml .Values.env | indent 12 }}
